name: Upload Instagram Reel Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  upload-reel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if session file exists
        id: check_session
        run: |
          if [ -f "./session.json" ]; then
            echo "Session file exists."
            echo "session_exists=true" >> $GITHUB_ENV
          else
            echo "Session file not found."
            echo "session_exists=false" >> $GITHUB_ENV
          fi

      - name: Run Python script to upload reel
        run: python autoupload.py
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}

      - name: Upload session file as artifact
        if: env.session_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: session-file
          path: ./session.json
