name: Upload Instagram Reel Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  upload-reel:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Download the session file if it exists
      - name: Download session file artifact (if exists)
        uses: actions/download-artifact@v3
        with:
          name: session-file
          path: ./  # Save session file in the current directory

      # Run Python script to upload reel
      - name: Run Python script to upload reel
        run: python autoupload.py
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}

      # Upload the session file as an artifact for future use
      - name: Upload session file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: session-file
          path: ./session.json
